target 'TwitterClient' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for Yelp
pod 'AFNetworking', '~> 2.5'
pod 'BDBOAuth1Manager'

end
